### ISSUE TITLE
Setup a server monitoring service

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#20]
We need to monitor the servers whether to tell us when they go down. In the past I have used Pingdom that can be configured to send us an SMS and Email when the server is down.
Pingdom: https://www.pingdom.com/

Let's ask Fran, he might have an alternate solution that does not require a paid service.

**Comment by frommberger** [comment]
What exactly do we need to monitor? Uptime? Responsiveness of the server software/website? Performance? Long-time monitoring? How fast do we need it? How long will it need to be reliably running?

If SMS is not essential, any open source solution or even a simple script that we could put on any other server would do.

**Comment by waidyanatha** [comment]
Most important is when the server goes down we are alerted. This is mostly for the production servers in the various countries. We could setup our demo server @AIT to ping those servers but that requires the server at AIT to be reliable. AIT is a 8am-4pm and 5 days a week operation. There's no one monitoring on the weekends and holidays.

**Comment by frommberger** [comment]
Best would be to set up two servers to monitor each other, one at AIT and one elsewhere. I could have my local server doing that. Setting up a Nagios service should not be too hard and should provide more options than we would ever need (except SMS, which we won't get for free).

**Comment by waidyanatha** [comment]
Let's try the Nagios service then, if we need SMS, we could use the AIT paid service. Are you able to write the script and pass it on to @biplovbhandari and @anggabayu21 to plant it in the AIT server?

**Comment by frommberger** [comment]
Nagios is a powerful toolkit that would be needed to installed and configured. In fact, one of the Nagios forks (Icinga, e.g.) would probably be a better solution. I won't be able to share a script, I might be able to set up the service here and then share the configuration files, but that would require a running service at AIT. It's a while since I used Nagios.

Do we have a list of servers and services we want to monitor?

**Comment by frommberger** [comment]
I have an Icinga service (a Nagios fork) running on my machine, it is currently monitoring the SAMBRO server at AIT plus the three servers in the countries. This works well, but I get a lot of messages about downtimes and not-reachable services. My impression is that this is more an issue of the connection to Germany.

Perhaps I could add @biplovbhandari to the recipients of the AIT server monitoring messages, to check whether the notifications are real issues or just false alarms?

**Comment by waidyanatha** [comment]
You can add both biplov and I to the service. Also when  @biplovbhandari
<https://github.com/biplovbhandari> come on line, sometime this week, we
can ask him to add the script on the the demo server at GIC.

**Comment by frommberger** [comment]
I set up everybody as indicated in your previous email. Currently, myanmar is down. Maldives does not receive any notifications as the service is flapping (going on and off continuously, that might be false alarm).

Moving this to AIT is not easy, it's not a script, but a complete Icinga installation (which turned out to be a nightmare to configure, unfortunately).
