### ISSUE TITLE
Warning priority added after creating new Scubscription

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#23]
When a subscriber adds a new subscription (/eden/default/index/subscriptions), sometimes the Implementer may have not yet defined a set of warning-priorities for the Event Type they select. The user can still save the record. 

What happens, later in time, when the implementer adds the warning-priorities? Does the subscriber automatically get updated to receive alerts to all the newly added warning-priorities for that event? Or what is the logic?

Perhaps we might need to build a mechanism that sends a weekly bulletin to all the users with the new updates so the Subscribers for example know that they need to make the corrections to their configurations?

**Comment by flavour** [comment]
This hasn't yet come up as a requirement, so Sahana currently has no ability to notify subscribers of new subscription options being available.
Is this really likely to happen often enough (weekly digest!? really?) to need to be automated through the system?
My first thought is that this would happen rarely enough for a manual communication to be the best solution. The system should be able to generate a report on the list of subscribers so that the communication can be sent and maybe provide a web form to have the message entered so that the user doesn't need to copy the subscriber list into their email & also that the communication is sent using the system email account rather than a personal one.

Referring to email:
* Twitter could also be used to send such updates instead/as well as email. Again I would do the update manually...although we could do this through the system to allow access to the official system account without needing to have the account details & to know which user sent the update.
* IFRC don't use Sahana's Subscription feature, so no learning to be done from there
