### ISSUE TITLE
Resouce block incomplete

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#44]
At present the resource block only allows for uploading images. See the CAP V1.2 specifications. It should allow for uploading any document, provide a URL to other resources that can be retrieved over the web and several other elements that are missing.

**Comment by waidyanatha** [comment]
All resources (documents, URLs) should be included in the Email when possible. The Subscriber should have the option of selecting whether or not they want to receive the resource files. 

One issue is if the resource file is too large then that may slow down the dissemination process with attaching each of the resources. You may have to do a performance computation to see when the file size increases how it slows down the process. Thereafter, we can set a constraint to limit the Resource file size and only those files that are below the constraint would be included in the Email as an attachment.

**Comment by frommberger** [comment]
I do not see an issue with the speed of dissemination if we are not talking about >>1000 recipients. Most of the time of email delivery is lost on DNS and SMTP connections, not I/O.

However, the size of the outgoing message must be monitored to not exceed a certain size, as incoming mail servers might have quite variable restrictions about acceptable mail sizes (usually, 10MB, but could be much less, nobody knows).

Another, safe option would be to reference to resources inline instead of attaching them, such that they will be fetched later when the email is read (which of course would require an active network connection at this point).

**Comment by waidyanatha** [comment]
That was our conclusion to provide the resource in-line for them to fetch it over an active network. 
Only the CAP.XML file would be provided in the email attachment. All other resources will simply carry the link in the body.

**Comment by biplovbhandari** [comment]
#39

**Comment by waidyanatha** [comment]
Reminder , you need to add the URL to the Blueprint and Userguide that discusses this feature
