### ISSUE TITLE
revise Email subject

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#61]
The email subject is duplicating words like Depression Depression; example: http://www.dmhwarning.gov.mm/eden/cap/public/1061.cap
that's because they are using the same word in the Headline and Event. Ideally, the users should catch this and correct them but they seem not to care. I wonder whether we should simply keep the subject to just the headline?

**Comment by biplovbhandari** [comment]
the subject is ([sender_name] event_type priority) currently. Maybe '[sender_name] event_type' alert be better?

**Comment by waidyanatha** [comment]
headline would be a bit more informative that event type; thus, [sender_name] + {headline] is better. let's try that see what happens.

**Comment by biplovbhandari** [comment]
That means most of time this will be default headline because there is 99%
chance that len > 78

On Nov 4, 2016 6:12 AM, "Nuwan Waidyanatha" <notifications@github.com>
wrote:

headline would be a bit more informative that event type; thus,
[sender_name] + {headline] is better. let's try that see what happens.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/sahana/SAMBRO/issues/61#issuecomment-258301644>, or mute
the thread

**Comment by waidyanatha** [comment]
yes I was thinking the same; given that the headline could be upto 140 chars. Shall we try:
[sender-name] + [event] + [msgType] ?

e.g. [Myanmar Department of Meteorology and Hydrology] Depression Update

**Comment by waidyanatha** [comment]
Still a small fix in that I emailed today. 
reference: https://github.com/sahana/SAMBRO/issues/60

Also need a link to wiki user guide and/blue print where we describe the formula for creating the email header; so implementers and future developers know.

**Comment by biplovbhandari** [comment]
http://eden.sahanafoundation.org/wiki/UserGuidelines/SAMBRO#SystemAdministrators

**Comment by waidyanatha** [comment]
Myanmar is still issuing alerts that has subject saying "Change Subject Header" . I thought you were going to truncate the header?

**Comment by biplovbhandari** [comment]
yes this is already fixed. can close now
