### ISSUE TITLE
CAP OID not showing after preload

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#82]
CAP OIDs are imported during preload in template = SAMBRO (which is the SAMBRO/Demo)
However, they are not displayed in the Organization form CAP OID field.
But they do show in the table

![screenshot from 2018-01-15 10-50-10](https://user-images.githubusercontent.com/543943/34925132-4f9b3858-f9e2-11e7-9462-800feb45be6c.png)

![screenshot from 2018-01-15 10-50-43](https://user-images.githubusercontent.com/543943/34925112-3743368e-f9e2-11e7-9cad-80d5d8f1fcda.png)

**Comment by nursix** [comment]
I don't think the cap_alerting_authority model is used in SAMBRO.

It certainly exists, and there are some prepop data for it in Demo and AlertHub, but there is no reference to it anywhere in CAP, nor in the SAMBRO template(s). So the prepop of cap_alerting_authority.csv, even though working, seems actually irrelevant.

The "CAP OID" form field in the organisation record refers to an organisation tag (table org_organisation_tag), with the tag name "cap_oid" - and that's also what is used to generate alert IDs. So one would assume that this is the intended data model, and hence CAP OIDs should be imported to that.

In order to prepop the cap_oid tag, it should be added as column "KV:cap_oid" to organisation.csv.

**Comment by waidyanatha** [comment]
The procedure with adding a column "KV:cap_oid" works! I have tested it and made the change to the sub-template SAMBRO/AlertHub prepop data. However, didn't cleanup the rest of the template yet; i.e removing the unnecessary cap_alerting_authority.csv file and removing or commenting out relevant line in the the task.cfg files.
