### ISSUE TITLE
ATOM parser to read CAP feeds

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#83]
Add code to parse and pull ATOM feed CAP messages into CAP tables.
follow:
https://github.com/sahana/eden/blob/master/modules/templates/SAMBRO/parser.py#L64
https://github.com/sahana/eden/blob/master/modules/templates/SAMBRO/parser.py#L236

example feed
http://meteoalarm.eu/ATOM/AT.xml

**Comment by flavour** [comment]
Generally, as far as Eden is concerned, ATOM should be treated just like RSS since both are parsed by the feedparser library: https://pypi.python.org/pypi/feedparser

However, of course this needs testing & there may be specific issues with a particular feed, but I suggest that as the right place to start....never know it might 'just work' already :)
